name: Build Widget

on:
  workflow_dispatch:        # Adds the manual run option
  push:
    branches: [ "main" ]    # Still runs automatically on push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node build.js --target=umd --minify
      - name: Upload dist directory
        uses: actions/upload-artifact@v4
        with:
          name: built-widget
          path: dist/
